:experimental:
ifdef::env-github[]
:icons:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Amalgam(ation)

[TIP]
====
AVX2 may be faster than SSE2 though not all CPUs support it (`Steam > Help > System Information > Processor Information > AVX2`). Freetype uses freetype as the text rasterizer and includes some custom fonts, which results in better looking text but larger DLL sizes. PDBs are for developer use.
====

WARNING: This fork of Amalgam uses AI heavily, it's primarily as a testbed for it.

Only link:https://github.com/DarthTon/Xenos/releases[Xenos] and "protecting" both Xenos and Amalgamation with Themida is recommended, don't use a VAC bypass as you'll get banned after too many reports.

== Building

. Ensure Visual Studio 2022 is installed with "Desktop development with C++".
. Change to ReleaseFreetype if your CPU doesn't have AVX2: +
`.\Build.ps1 -ProjectPath "Amalgam.sln" -Configuration "ReleaseFreetypeAVX2" -Platform "x64"`
- Alternatively you can use Visual Studio 2022 to compile.
